### ISSUE TITLE
Add Noto font

### ISSUE THREAD

**Issue by waldyrious** [alfredxing/brick#1]
The [Noto font](https://code.google.com/p/noto/) is a very promising and ambitious font aimed at covering all scripts in current usage (the name stands for "no tofu") under a visually harmonious font. The stable release covers Latin, Cyrillic and Greek, but more families are [already on track for release soon](http://www.google.com/fonts/earlyaccess) covering several other scripts. "Our current plan is to support all living scripts in Unicode by the end of 2014."

There are two families available in Google Fonts: [Noto Sans](http://www.google.com/fonts/specimen/Noto+Sans) and [Noto Serif](http://www.google.com/fonts/specimen/Noto+Serif).

**Comment by alfredxing** [comment]
Thanks for the suggestion. I'll add it soon!

**Comment by waldyrious** [comment]
yay! :+1:

**Comment by alfredxing** [comment]
Done. You might want to test it out.

Reopen if you have any issues!

**Comment by waldyrious** [comment]
Thanks for doing this so quickly! I added this to a site I was using Noto on, but didn't notice any improvements:
![Imgur](http://i.imgur.com/T24tCG3.png)

Is this expected?

Also, I find that the page takes longer to load.

([Link to Google Fonts version](http://htmlpreview.github.io/?https://github.com/waldir/learning-holography/blob/56ef58cb15fe97dadae041ab342bce2d6f39b3e1/index.html) / [Link to Brick version](http://waldir.github.io/learning-holography/) / [The change I made to the code](https://github.com/waldir/learning-holography/commit/f928788))

**Comment by alfredxing** [comment]
In this case, Noto is a TTF font, so you won't see a huge difference in rendering (OTF/PostScript fonts usually render better).

Add this CSS; it makes fonts with kerning and ligature data render a lot better:

``` css
body {
    -webkit-font-feature-settings: "kern", "liga";
    -moz-font-feature-settings: "kern", "liga";
    font-feature-settings: "kern", "liga";
    text-rendering: optimizeLegibility;
}
```

As for speed, it is a bit slower since we don't subset, while in your Google Fonts version, you chose to subset with Latin and Latin Extended. Noto, as you mentioned above, contains most UTF-8 characters, so its size is large—around 300KB.

**Comment by waldyrious** [comment]
Oh, ok, thanks for the detailed explanation. I made the change as you suggested, and indeed kerning was improved (I don't think Noto has ligatures yet). The smoothness of outlines hasn't, but it's no worse than GF. Would subsetting work for Brick as well? Should I make a separate feature request for that?

**Comment by alfredxing** [comment]
I'm pretty sure subsetting is a form of modification, and we may run into licensing problems there. But go ahead and make a feature request, we'll see how many people want that and perhaps we can figure out a way.
