### ISSUE TITLE
Remove SVG support

### ISSUE THREAD

**Issue by alfredxing** [alfredxing/brick#102]
Just a couple of weeks after SVG support was added in #85, Chrome's stable channel was promoted to version 37, which included DirectWrite support as default. With this, WOFF files rendered much better, making SVG's not as advantageous as before.

The SVG's take up a lot of space in the repository, and add quite a bit of complication to the font addition process.

I just wanted to start a discussion about whether SVG support can/should be removed. What do you think?

**Comment by fitojb** [comment]
The SVG format is [deprecated for fonts](https://github.com/adobe-fonts/source-sans-pro/issues/46#issuecomment-49169190), and major vendors, such as Adobe, no longer promote it. Please go ahead in removing it.

**Comment by jensscherbl** [comment]
+1

**Comment by alfredxing** [comment]
SVG support is already removed. Forgot exactly when, but the files aren't in the repo anymore.
