### ISSUE TITLE
Charter?

### ISSUE THREAD

**Issue by curiositry** [alfredxing/brick#110]
Charter is freely available now, any thoughts about adding it?

More info + licence here: http://practicaltypography.com/charter.html

**Comment by alfredxing** [comment]
Looks like a high quality font! Reminds me of some others in the catalogue (Droid Serif, PT Serif).
It's finals season right now, so I probably won't be doing anything until start/mid-May.

Thanks as always for contributing! :heart:

**Comment by alfredxing** [comment]
Merged in #127
