### ISSUE TITLE
Source Sans Pro 400 is returning a 404

### ISSUE THREAD

**Issue by cbulock** [alfredxing/brick#112]
https://brick.a.ssl.fastly.net/fonts/sourcesanspro/400.woff is being returned as the URL for the 400 weight on the Source Sans Pro font, but that is giving a 404 error.

**Comment by cbulock** [comment]
Turns out this was a temporary issue, appears to be resolved already

**Comment by alfredxing** [comment]
Thanks for reporting. This is the same issue as #113. I believe it was temporary only because Fastly detected the error and started serving its cached copy from backup. The error did exist on the origin server until I fixed it just then.

Sorry for the inconvenience!
