### ISSUE TITLE
Lato Medium Missing (404) w/ http?

### ISSUE THREAD

**Issue by nemosupremo** [alfredxing/brick#113]
Thanks for these fonts - however we started noticing the `Lato 500` throws a 404 errorwhen used with http (http://brick.a.ssl.fastly.net/fonts/lato/500.woff).

**Comment by alfredxing** [comment]
Thanks for reporting this! The 404 was caused by the recent move to Collections--the `font` directory was renamed to `_fonts`, which didn't play well with our nginx config.

This should be fixed now. Extremely sorry for the inconvenience!
