### ISSUE TITLE
Support all 5+ Montserrat styles

### ISSUE THREAD

**Issue by mike-hearn** [alfredxing/brick#117]
I just wanted to give you a heads up that, while Google Fonts only includes two Montserrat styles, there are actually at least five total weights. Brick.im currently has "Regular" and "Bold", but there are also "Light", "Thin" and "Black". Montserrat is an amazing font - one of the best freely available fonts, in my opinion - and the added styles would be good additions to brick.im.

The Google Fonts GitHub has the TTF files: https://github.com/google/fonts/tree/master/ofl/montserrat

There are even more styles available at Font Squirrel, including "Semi Bold" and "Extra Bold", though I don't know the origin of those styles so I hestitate to advocate including those as well: http://www.fontsquirrel.com/fonts/montserrat

**Comment by alfredxing** [comment]
Thanks! I'm quite busy right now, but I will add these when I have some time!

**Comment by phoenixenero** [comment]
I found the original Montserrat fonts here: https://github.com/JulietaUla/Montserrat

Will PR tomorrow.

**Comment by alfredxing** [comment]
Merged in #131!
