### ISSUE TITLE
Add Linux Libertine

### ISSUE THREAD

**Issue by curiositry** [alfredxing/brick#13]
I would suggest adding the [**Linux Libertine**](http://www.linuxlibertine.org/) family to Brick. It is a great typeface with all the bells and whistles — small-caps, italics, open-type features, etc.

This looks like a great project!
- [x] [**Linux Libertine**](http://www.linuxlibertine.org/)

**Comment by alfredxing** [comment]
Thanks! I'll add that soon.
Note that I'm only considering Linux Libertine's regular text variant and that for now Brick won't support small caps (since `@font-face` requires it to be a separate font family).

**Comment by alfredxing** [comment]
Added & closing.
