### ISSUE TITLE
Add Bitter

### ISSUE THREAD

**Issue by bouchard** [alfredxing/brick#14]
It'd be great if you could add Bitter (from Google Fonts), I'm using it for titling. The rendering of brick.im (particularly) on Windows is starkly better, great work!

**Comment by alfredxing** [comment]
Already requested in #8, closing.

**Comment by bouchard** [comment]
My apologies, he beat me to it. Thanks!

**Comment by alfredxing** [comment]
No problem, thanks for contributing!
