### ISSUE TITLE
Permission to show a screenshot of Brick in an upcoming book about web design?

### ISSUE THREAD

**Issue by tracymakes** [alfredxing/brick#148]
Hey there,

I'm writing and self-publishing a book teaching beginner web design aimed at programmers/developers titled Hello Web Design (https://hellowebbooks.com/learn-design/)

I'm a big fan. May I use a screenshot in the book?

How it'll look: https://www.dropbox.com/s/8o0rw37342wtiim/Screenshot%202017-08-07%2019.18.19.png?dl=0

Additional information:
— The link below is a redirect and will redirect to your website (I have it set up that way so I can update links in case your website's URL ever changes.) 
— There is a chapter at the book listing all link references, and the specific page linked will be listed in full there.
— I will be selling this book through my website (https://hellowebbooks.com) as well as through Leanpub (https://leanpub.com) and Amazon.

Let me know if this is okay or not, if you'd like any changes, or any other questions you may have. :)

Cheers,
-Tracy

**Comment by alfredxing** [comment]
@limedaring Thanks for reaching out! This is totally fine by me, thanks for the mention 🙂 

Let me know if you have any questions, otherwise feel free to close the issue.

**Comment by tracymakes** [comment]
Thank you! 🙌
