### ISSUE TITLE
Font Collection

### ISSUE THREAD

**Issue by noahbuscher** [alfredxing/brick#15]
Possibly a feature that would allow you to pick an choose fonts and add them to a collection that gave you a URL to include them all, just like how [Google Fonts](http://google.com/fonts) does it. I may be able to code this feature this week.

**Comment by alfredxing** [comment]
That would be awesome!

**Comment by noahbuscher** [comment]
Cool! I'll see what I can do later this week. I'm kind of busy with school an another application I'm building, but I should totally be able to make time.

**Comment by fluke** [comment]
This is definitely needed. I'll try submitting a pull request next weekend.

**Comment by alfredxing** [comment]
Added with the last redesign. Thanks!
