### ISSUE TITLE
Please enable IPv6 and HTTP/2 support

### ISSUE THREAD

**Issue by nagisa** [alfredxing/brick#150]
So the URL like `https://brick.dualstack.g.shared.global.fastly.net/fonts/` would "just" work.

See https://www.fastly.com/blog/ipv6-fastly.

**Comment by alfredxing** [comment]
Sorry about lack of action on this — this project is _basically_ in maintenance mode now, I don't have much bandwidth to work on it.

However, I'm doing some backend changes now (I need to renew the servers) so I'll loop this in. Thanks for using Brick!

**Comment by alfredxing** [comment]
Done in #153 🎉
To activate you'll have to change your CSS URL to use `//brick.freetls.fastly.net`.
