### ISSUE TITLE
Error 503 Backend is unhealthy

### ISSUE THREAD

**Issue by vguenichon** [alfredxing/brick#155]
I call this : //brick.freetls.fastly.net/Open+Sans:300,400,600,700,900,300i,400i,600i,700i,900i/Montserrat:100,200,300,400,500,600,700,800,900
And get a 503 error.
Any idea ?
The page where you can see it in action : http://www.antidot.net/contact/
Thanks a lot

**Comment by NetOpWibby** [comment]
I'm getting this issue too. Unfortunate.

**Comment by alfredxing** [comment]
So sorry about this! I had set up alerting but it didn't seem to work. The site should be fixed now (was a backend server issue as the error mentioned) and I will look into how the monitoring broke.
