### ISSUE TITLE
Merriweather returns a 404

### ISSUE THREAD

**Issue by chrisfinazzo** [alfredxing/brick#156]
Getting this error on one of my sites where I have the following font URL:

`https://brick.a.ssl.fastly.net/fonts/Merriweather/700.woff`

Is this because of #153, perhaps?

**Comment by alfredxing** [comment]
Hi! I don't believe so... are you referencing that URL directly in your code, or using the CSS generation? In either case the font name should be lowercase (i.e. `https://brick.a.ssl.fastly.net/fonts/merriweather/700.woff` should work)

**Comment by chrisfinazzo** [comment]
Huh. I guess older versions were somehow less strict about this and didn't choke on it. I'll regenerate this and check again to make sure it works.

**Comment by chrisfinazzo** [comment]
I think this is correct, different fonts, but regenerates and everything loads.

```
@font-face {
    font-family: 'Cardo';
    font-style: normal;
    font-weight: 700;
    src: local('Cardo-Bold'), url(//brick.freetls.fastly.net/fonts/cardo/700.woff) format('woff')
}

@font-face {
    font-family: 'Source Sans Pro';
    font-style: normal;
    font-weight: 400;
    src: local('Source Sans Pro Regular'), url(//brick.freetls.fastly.net/fonts/sourcesanspro/400.woff) format('woff')
}

@font-face {
    font-family: 'Source Serif Pro';
    font-style: normal;
    font-weight: 400;
    src: local('Source Serif Pro'), url(//brick.freetls.fastly.net/fonts/sourceserifpro/400.woff) format('woff')
}
```
