### ISSUE TITLE
Required Attribution / Commercial use

### ISSUE THREAD

**Issue by kmpoppe** [alfredxing/brick#163]
Hi!

I'm planning on unsing a Brick Font on a commerical website, and even though I found Websites using Brick in the Wiki, I wasn't able to find any information on what License this project uses and/or what attribution you'd like to be shown on the websites using the fonts?

Due to German and EU regulations I will be downloading the stylesheet and the woff file to the local webserver to prevent transferring data outside the EU (which would happen because of the use of Fastly). If there'd be any objections from your side, please let me know!

Thanks!

Kai

**Comment by alfredxing** [comment]
Hi! The license of the font you are using should be available in the LICENSE file next to the font files in this repo, e.g. https://github.com/alfredxing/brick/blob/gh-pages/_fonts/inconsolata/LICENSE

The source code for Brick itself is not licensed but that shouldn't be an issue if you are just using the fonts. The stylesheets produced by Brick are not copyrighted.
