### ISSUE TITLE
live preview

### ISSUE THREAD

**Issue by bsdlp** [alfredxing/brick#19]
It would be great if the specimen page could utilize the fonts provided by brick and provide a form for a live preview.

For example, font shop's "Enter sample text":

http://www.fontshop.com/fonts/foundry/hurme_design/

In addition, this would eliminate a step in the woff creation process, essentially making it all automated and easy.

**Comment by alfredxing** [comment]
See @3. It's a big tradeoff, especially when we want to showcase the font's quality as well (Google Fonts compresses its preview fonts even more than what it serves).
