### ISSUE TITLE
using in rails

### ISSUE THREAD

**Issue by vjaykoogu** [alfredxing/brick#20]
How can i use it on ruby on rails. ?

**Comment by alfredxing** [comment]
Check the [Usage](https://github.com/alfredxing/brick/wiki/Usage) page in the wiki.

I'm not too familiar with Rails, but I know you need to put the `<link>` tag in the `<head>` section of your layout (usually `application.html.erb`).

You can also Google "use Google Web Fonts in Rails". It's pretty similar; just replace the link asset URL with Brick's.
