### ISSUE TITLE
Extract font catalog into YAML file

### ISSUE THREAD

**Issue by hnrch02** [alfredxing/brick#22]
Continuation of the discussion in #21

If we were to extract the font catalog from the PHP file into its own, dedicated YAML file, we could use that data in Jekyll for GitHub Pages.
I learned that PHP has in fact no native support for parsing YAML so, @alfredxing can you install and use [PECL extension](http://www.php.net/manual/en/book.yaml.php) wherever the PHP file is running?

**Comment by alfredxing** [comment]
I'm currently unable to install PECL extensions, but Symfony has a YAML component (http://symfony.com/doc/current/components/yaml/introduction.html).

Again, my main concern is speed. Both reading the file and parsing the YAML are the most expensive and second-most expensive parts of the script.

**Comment by hnrch02** [comment]
Both these actions would only need to be run once on startup and could then be read from the cache, couldn't they?

**Comment by alfredxing** [comment]
@hnrch02 True. I'm not too familiar with PHP caching, if you want to implement it feel free to submit a pull request.

There's also the problem of the data file living in the `[gh-pages]` branch, and `index.php` in the master branch.

**Comment by bsdlp** [comment]
why not simply copy over the jawns from master into gh-pages, and make gh-pages the master branch in GitHub?

**Comment by alfredxing** [comment]
@fly I wouldn't be too fond of the directory structure, but it would mean we can use Jekyll to generate both `index.php` and `fonts/index.html`...

**Comment by hnrch02** [comment]
If I may ask, where is this PHP hosted and are there any other language options than PHP?

**Comment by bsdlp** [comment]
@alfredxing IMO the directory structure would actually make more sense. index.html in the fonts dir, another index.html in each of the font dirs as well.

**Comment by alfredxing** [comment]
@fly Then each `index.html` in each font directory would preview the font! Genius!

I'll make the branch changes now; the Jekyll changes will come later once I figure that out.

**Comment by bsdlp** [comment]
:shipit:

**Comment by alfredxing** [comment]
Done, marking as closed. Thanks!
