### ISSUE TITLE
Add Lato

### ISSUE THREAD

**Issue by alfredxing** [alfredxing/brick#24]
Forgot to add Lato in the beginning, will add it soon.
- [x] Lato

**Comment by WojciechWyszynski** [comment]
Please add also "Titillium Web", it's a very popular font.

**Comment by alfredxing** [comment]
@Nevide Please open up a separate issue for this; it's a bit easier to keep track. Thanks!

**Comment by JerrySievert** [comment]
+1

**Comment by alfredxing** [comment]
@JerrySievert This is where multiple fonts per issue gets confusing... +1 for Lato or Titllium?
I'll add Lato soon, but Titillium might have to wait a bit.

**Comment by JerrySievert** [comment]
@alfredxing the original issue, of course :)  Lato.  new fonts are new issues.

thanks!

**Comment by fluke** [comment]
+1

**Comment by alfredxing** [comment]
Done! I also added a webhook so that the server pulls with every push automatically (instead of me having to log in to manually do it).

**Comment by JerrySievert** [comment]
Awesome!  Thanks much, and great work!

:thumbsup:

**Comment by fluke** [comment]
Excellent.

**Comment by alfredxing** [comment]
@JerrySievert @kartikluke Thanks!

**Comment by OutThisLife** [comment]
Is it just me or does the Lato look really bad?

From Google Fonts: http://d.pr/i/KY7t
From Brick: http://d.pr/i/YExN

**Comment by alfredxing** [comment]
@OutThisLife That does look bad. What browser/OS?

**Comment by OutThisLife** [comment]
Windows 7, FF 30

**Comment by alfredxing** [comment]
Interesting, especially for Firefox... How does [this page](http://brick.im/fonts/lato/) look?
