### ISSUE TITLE
Incorrect response in Usage page

### ISSUE THREAD

**Issue by jeluard** [alfredxing/brick#26]
[Usage](https://github.com/alfredxing/brick/wiki/Usage) mentions response looks like `... url(//brick.a.ssl.fastly.net/ebgaramond/400.woff) ...` but it has been recently modified to `... url(//brick.a.ssl.fastly.net/fonts/ebgaramond/400.woff) ...`.

I would have changed it myself but I don't think you can make pull request for wiki pages.

**Comment by alfredxing** [comment]
Thanks for telling me about the error!
Hmm, it's called 'wiki' for a reason. You should be able to edit it... Do you see an "Edit" button on the top right?

**Comment by jeluard** [comment]
I don't actually. Probably only contributors to a project do see it.

**Comment by alfredxing** [comment]
That's interesting...
Direct quote from the settings page of this repo:

> GitHub Wikis are the simplest way to let others contribute content. Any GitHub user can create and edit pages to use for documentation, examples, support or anything you wish.

Anyway, I'll look into that and fix it for now.
Thanks!

**Comment by alfredxing** [comment]
Emailed GitHub support and it seems that I had the "no-edit" box checked for some reason. Th wiki should be editable now!
