### ISSUE TITLE
Ability to set your own example text

### ISSUE THREAD

**Issue by catmanjan** [alfredxing/brick#3]
Hi, not sure what the "kiwi jam" thing is, but it would be nice if you could set the text you want previewed on the font page of the web site.

Cool project though, thanks!

**Comment by alfredxing** [comment]
It is indeed a really nice feature to have. However, this can be achieved in only 2 ways: to load all the fonts or to use a backend image generator. The former would take way too long for the end user, and I don't have the computing power for the latter.

If you know a better way, by all means, tell me! But for now, marking this as `wontfix`.

**ProTip**: A quick way to preview is just to make a quick HTML page and drag it into your browser.

**Comment by catmanjan** [comment]
It's 2014, loading a megabyte or so of web fonts (asynchronously btw) isn't really an issue. 

The images themselves are already half that.

**Comment by alfredxing** [comment]
It's actually around 6MB; the images are around 400KB.

Although Fastly's infrastructure is extremely stable, I don't want to create 6 megs of bandwidth every time a user visits the site.
:sweat_drops:

I'll think about it some more for sure.
