### ISSUE TITLE
Add Merriweather

### ISSUE THREAD

**Issue by fluke** [alfredxing/brick#32]
- [x] Merriweather

https://www.google.com/fonts/specimen/Merriweather
http://www.google.com/fonts/specimen/Merriweather+Sans

**Comment by fluke** [comment]
https://github.com/EbenSorkin/Merriweather This may be the source.

**Comment by blaenk** [comment]
I hate +1 comments, but seeing as I imagine it'd be useful to have a way to decide which fonts to add, I also want to express that I would love to have Merriweather supported :)

**Comment by ghost** [comment]
Merriweather ♥

**Comment by alfredxing** [comment]
@blaenk +1 (:+1:) comments are useful, especially when it comes to something like requesting fonts. It lets me gauge the demand for a font so I know which ones to prioritize.

@davidossahdez I know, I know. I'll be adding it :soon:!

**Comment by alfredxing** [comment]
Added. Enjoy!

**Comment by fphilipe** [comment]
Any chance of including Merriweather Sans as well? :blush: Would love to switch from Google Fonts to Brick, but unfortunately this is a show stopper :cry:
