### ISSUE TITLE
Add Typeface to listings

### ISSUE THREAD

**Issue by jess-sol** [alfredxing/brick#35]
It'd be nice to have the type face (serif, sans-serif, monospace, etc) listed with the font.  For example, right now I'm looking for a monospace font for to display code with and it'd be great if I could just search for monospace to find the fonts I'd be interested in.

It seems some have sans or serif appended to the name, but it isn't consistent enough to be able to search on with confidence.

**Comment by alfredxing** [comment]
Seems like a great idea!
I'll likely be working on a new site/interface soon, so stay tuned!

**Comment by alfredxing** [comment]
Added in the last redesign. Thanks for contributing!
