### ISSUE TITLE
Add Playfair Display

### ISSUE THREAD

**Issue by bloccxx** [alfredxing/brick#37]
- [x] Playfair Display

Would love to have em!

**Comment by iangeek** [comment]
+1 for Playfair Display. Be good to have a serif with more didone-like contrast and ultra-heavy weight

**Comment by alfredxing** [comment]
Looks good!
@panameraa Can you make a separate issue for each font though? It's easier to keep track that way. This one will be for Playfair.

Official website: http://www.forthehearts.net/typeface-design/playfair-display/
Source files: http://googlefontdirectory.googlecode.com/hg/ofl/playfairdisplay/src/

**Comment by bloccxx** [comment]
Added new issues.  
Thank you!

**Comment by alfredxing** [comment]
Added in commit d36719f3e49c3af8afc9109cda5768a95bccb9ce. Enjoy!
