### ISSUE TITLE
Add Comic Neue

### ISSUE THREAD

**Issue by bsdlp** [alfredxing/brick#38]
- [ ] Comic Neue

http://comicneue.com/

> No attribution is required

http://comicneue.com/comic-neue.zip

**Comment by alfredxing** [comment]
Umm...
Marking for feedback from others.

**Comment by niutech** [comment]
+1 for adding Comic Neue to the CDN. It would be used by [Comic Sans Replacer](https://github.com/niutech/comic-sans-replacer) for faster loading times.

**Comment by alfredxing** [comment]
@niutech For your usage I recommend creating an official Chrome extension with the font packaged in, since even developer extensions get disabled by the browser automatically on startup.

**Comment by niutech** [comment]
Comic Sans Replacer is now in Chrome Web Store (https://chrome.google.com/webstore/detail/comic-sans-replacer/hogcjpgnoecbkmbamlakaacafkloopbn) and Comic Neue is on jsDelivr CDN (http://www.jsdelivr.com/#!comic-sans-replacer).

**Comment by curiositry** [comment]
+1 for a tasteful comic font.

**Comment by alfredxing** [comment]
@niutech I like how you listed the extension under "accessibility". :clap:

Due to popular demand, I'll add it.

**Comment by alfredxing** [comment]
Added, closing. Enjoy!
