### ISSUE TITLE
Monospace typefaces

### ISSUE THREAD

**Issue by bsdlp** [alfredxing/brick#4]
Please add these monospace jawns!
- [x] [Inconsolata](http://levien.com/type/myfonts/inconsolata.html) ef6661ca99feee21ce3585479947ad1cca426392
- [x] [Anonymous Pro](http://www.marksimonson.com/fonts/view/anonymous-pro)
- [x] [Source Code Pro](https://github.com/adobe/source-code-pro)

**Comment by alfredxing** [comment]
Those were definitely left out. Adding soon!
:+1:

**Comment by alfredxing** [comment]
Inconsolata is done. I'll add the other two tomorrow.

**Comment by alfredxing** [comment]
Added Source Code Pro.

**Comment by albertxing** [comment]
Monospace fonts shouldn't have ligatures in the preview

![screen shot 2014-03-17 at 10 06 00 am](https://f.cloud.github.com/assets/2881206/2438827/75d40a5e-adf6-11e3-88af-33375087e929.png)

**Comment by alfredxing** [comment]
Oops. I'll redo that one.

**Comment by alfredxing** [comment]
Added Anonymous Pro; closing.

**Comment by bsdlp** [comment]
:+1:
