### ISSUE TITLE
Specimen page for each font

### ISSUE THREAD

**Issue by ghost** [alfredxing/brick#43]
Although I can go to Google to see a sample specimen page for each font on brick.im, it will be useful to have them in the brick site itself. The user can click the image preview and land in a page similar to this: http://brick.im/preview/brick.html but for every font on the site. Those specimen pages are really useful to check the readability of the fonts before using them.

**Comment by alfredxing** [comment]
@davidossahdez I've been thinking about this as well, but it adds a great deal of work to the font uploading process. Do you know of a way to automatically generate these pages with Jekyll?

**Comment by ghost** [comment]
@alfredxing Sorry but I've never used Jekyll before

**Comment by alfredxing** [comment]
@davidossahdez That's fine. Leaving open for suggestions.

**Comment by alfredxing** [comment]
Was added a pretty long time ago, closing. Thanks for the suggestion!
