### ISSUE TITLE
Help classify fonts!

### ISSUE THREAD

**Issue by alfredxing** [alfredxing/brick#50]
I'm working on an enhanced version of the catalogue, which will allow everyone to filter by certain font properties.

For now I've added the classification (serif, sans serif, or monospace) and suggested usage (display or body). While all of the classification fields are filled out, most of the usage fields are blank (for you to fill out!).

Feel free to fill these out and/or add more properties (maybe a `type` property to elaborate on the `class` property. and which contains a more specific classification (modern, transitional, humanist, geometric, etc.)

The file is at [`[catalogue]/_data/fonts.yaml`](https://github.com/alfredxing/brick/blob/catalogue/_data/fonts.yaml).

Happy forking! :octocat:

**Comment by namanyayg** [comment]
404 on the link? 

Is there any one single data file, or have they moved to individual sections (Like [Oswald's](https://github.com/alfredxing/brick/blob/catalogue/_fonts/oswald/index.html), for example)?

**Comment by alfredxing** [comment]
Sorry about that. All of the fonts week classified already; this issue should have been closed.

Thanks for bringing this up!
