### ISSUE TITLE
Font Suggestion:  Add Linux Biolinum

### ISSUE THREAD

**Issue by simonwiles** [alfredxing/brick#51]
- [ ] Linux Biolinum

Thank you for providing such a great service, and in particular for making the awesome Linux Libertine available.  Would you also consider adding its sister font, Linux Biolinum, to the collection?  Like Linux Libertine, it's GPL and OFL, and the homepage is here: http://www.linuxlibertine.org.

These two fonts are especially useful for the complete set of diacritical marks they carry.

(Note: the WOFF files are already created, and available at the source site)

**Comment by alfredxing** [comment]
Thanks! Adding Biolinum to the queue.

**Comment by simonwiles** [comment]
Cheers :)  I'd do the pull request, but I can't work with the .ai file (it won't open properly in Inkscape).

**Comment by alfredxing** [comment]
@simonwiles You can send in the pull request and I can add that in later if you'd like.
