### ISSUE TITLE
Add Source Serif Pro

### ISSUE THREAD

**Issue by curiositry** [alfredxing/brick#54]
Another adobe font designed to pair with Source Sans Pro.

Find it here: https://github.com/adobe/source-serif-pro

**Comment by alfredxing** [comment]
Is this new? Great!

**Comment by curiositry** [comment]
Yep — first commit 8 days ago. Looks like a nice font, too!

**Comment by alfredxing** [comment]
I'll download from http://sourceforge.net/projects/sourceserifpro.adobe/ since that seems to be where the actual releases are.

**Comment by alfredxing** [comment]
Added in referenced commit.
