### ISSUE TITLE
Computer Modern Concrete

### ISSUE THREAD

**Issue by ColeTownsend** [alfredxing/brick#57]
This would be super to have. I've tried serving it and it's always slow.

[Source](http://checkmyworking.com/cm-web-fonts/)

**Comment by alfredxing** [comment]
Awesome, we'll see if anyone else is interested (otherwise I'll add it later).
Would you consider this slab serif or serif?

**Comment by ColeTownsend** [comment]
It’s definitely a slab serif, albeit a bit on the less weighty side compared to most.

**Comment by elliottslaughter** [comment]
I would vote for this if it also included the regular CM font (not concrete).

Regarding the source: I believe the more official source for OTF-ized CM is on CTAN: http://www.ctan.org/pkg/cm-unicode . The original link appears to be someone's personal homepage.

**Comment by alfredxing** [comment]
@elliottslaughter Brick already has Latin Modern, which is a successor to the CM family (they're really similar, actually; LM just extends and optimizes the CM family).
