### ISSUE TITLE
Add Gotham font?

### ISSUE THREAD

**Issue by Kikobeats** [alfredxing/brick#58]
link related:

http://thenextweb.com/twitter/2014/05/31/twitter-com-says-goodbye-helvetica-neue-hello-gotham/

http://www.theverge.com/2014/5/30/5766106/twitter-quietly-changes-its-font-from-helvetica-neue-to-gotham

**Comment by Kikobeats** [comment]
Ok the problem is the license. Shit.

**Comment by alfredxing** [comment]
I wish it was free too :cry:
