### ISSUE TITLE
Catalogue link is 404

### ISSUE THREAD

**Issue by curiositry** [alfredxing/brick#63]
http://brick.im/fonts/ goes to "There isn't a GitHub Page here."

**Comment by namanyayg** [comment]
Same.

Edit: Seems like #62 is the cause. Oh well.

**Comment by alfredxing** [comment]
Yeah, as @namanyayg mentioned, it's due to Jekyll being outdated on their side (#62). I've gotten an email response back from them, the rough response is posted in that issue.

Closing as duplicate.
