### ISSUE TITLE
Add to bucket doesn’t work in Firefox 30

### ISSUE THREAD

**Issue by curiositry** [alfredxing/brick#66]
The + (add to bucket) buttons are not working for me. I’m running the latest firefox on Ubuntu 14.04 LTS; I tested it in Chromium and it worked fine, though.

**Comment by alfredxing** [comment]
Can you open DevTools and see if there are any error messages?

**Comment by curiositry** [comment]
No errors are thrown. 

I was wrong about it not working at all; it does add to the bucket (I just discovered), but the bucket counter doesn’t update, it and it fails to generate the CSS when you select weights.

I threw some screenshots up here: http://imgur.com/a/Z0uEH#0

I added Alegreya, and the counter didn’t update; then I opened the bucket and you can see that it failed to generate the CSS, and when you click on a weight it says 'undefined'. I tried adding Lato, with the same result.

**Comment by alfredxing** [comment]
Interesting... What's the value of the global variable `bucket` at that point (you can check with the JS console).

**Comment by curiositry** [comment]
Bucket is an empty object.

**Comment by alfredxing** [comment]
Okay, I seem to have found the issue. It's with Firefox not supporting `innerText`, which I use all over the place. I don't have much time right now, but I'll replace all instances of `innerText` with `innerHTML` soon.

**Comment by hnrch02** [comment]
How about [`textContent`](https://developer.mozilla.org/en-US/docs/Web/API/Node.textContent)?

**Comment by alfredxing** [comment]
Yeah, `textContent` would work. Thanks!

**Comment by alfredxing** [comment]
Should be fixed in 6631d303d05fa4e861c3cae6d2ebd840393dc7a3. Let me know if you're still having issues!

**Comment by curiositry** [comment]
Good. It works now.
