### ISSUE TITLE
Add Lora

### ISSUE THREAD

**Issue by KyleAMathews** [alfredxing/brick#68]
http://www.cyreal.org/2012/07/lora/

Used on BoingBoing e.g. http://boingboing.net/2014/07/03/if-you-read-boing-boing-the-n.html

**Comment by curiositry** [comment]
Lora’s a great font IMHO — not a full family, but it has the essentials. + 1 for adding it.

**Comment by alfredxing** [comment]
Added, thanks for the suggestion!
