### ISSUE TITLE
Cardo - Font Suggestion

### ISSUE THREAD

**Issue by elliottslaughter** [alfredxing/brick#78]
Homepage: http://scholarsfonts.net/cardofnt.html

Google Web Fonts entry: https://www.google.com/fonts/specimen/Cardo

A font for "classicists, Biblical scholars, medievalists, and linguists".

Open font license.

**Comment by curiositry** [comment]
+1

**Comment by alfredxing** [comment]
Added, here's the specimen page (please test it out and tell me if you have any rendering issues, etc.): http://brick.im/fonts/cardo/

**Comment by curiositry** [comment]
Looks like the fi ligature in **overfilled** is there for the normal and italic, but not the bold. It might be a problem with the font itself, though.

**Comment by elliottslaughter** [comment]
According to the release notes for the font, this is "The first Cardo bold ever; limited character set but functional for many things such as headings." So I'm guessing that ligatures are not part of the "limited character set".

**Comment by alfredxing** [comment]
@omphalosskeptic @elliottslaughter Nope, just checked the font and it doesn't seem the bold version has an `fi` ligature, though the `ff`, `ffi`, and `ffl` ligatures are there.
