### ISSUE TITLE
Fonts still look bad on Chrome on Windows

### ISSUE THREAD

**Issue by fluke** [alfredxing/brick#79]
![image](https://cloud.githubusercontent.com/assets/3857139/3732953/eab613e2-1702-11e4-840a-d27ed83187b5.png)
As you can see this Merriweather image has a lot of artifacts. The solution used to be to download the font and use the svg file as the default rather than the other formats. Is it possible for you to do the same? As noted here its possible to specifically target webkit browsers with svg. http://www.adtrak.co.uk/blog/font-face-chrome-rendering/#fix

I can do these changes on my own obviously. But Brick.im fonts don't actually look good on the majority browser and if you can have this fix inbuilt. It'll make your service far more useful.

**Comment by fluke** [comment]
I just noticed that the readme specifies that you serve woff files specifically. But I still feel that you could provide a solution for this with your current setup and you'll make a lot of people happy.

**Comment by alfredxing** [comment]
I think providing SVG as an option would be a good idea. At the very beginning of Brick (before it even officially launched, I think), users had the option to choose between TTF, OTF, WOFF, and SVG (or all of them), but it ended up taking way too much space in the repository.

**Comment by fluke** [comment]
Sure. But I still think woff is a good format. We just need to provide svg
as well with the media query to target it. I'd like to help to set this up.
How can I contribute?

**Comment by alfredxing** [comment]
It's going to be tough getting all the SVG's, but you can get started on the PHP if you'd like. You'll want to look over the existing code to understand it, and add an `s` flag to trigger inclusion of the SVG file with the media query.

**Comment by fluke** [comment]
I was gonna get fontforge. Can't we just convert the current woffs to svg?
I can help out with that as well.

**Comment by iangeek** [comment]
Just an aside, but the current build of Canary looks to have resolved the font anti-aliasing issue so the problem may be moot before too much longer.

**Comment by iangeek** [comment]
Info here - http://blog.chromium.org/2014/07/chrome-37-beta-directwrite-on-windows.html

**Comment by alfredxing** [comment]
@iangeek You're right; it's on Chrome Beta as well, so it's probably not long before it moves to stable as well.

@kartikluke It's a bit complicated because the SVG fonts FontForge generates are missing a line of code that makes it incompatible with Chrome (so you'll need a more advanced script). I'll get back to you on that.

**Comment by fluke** [comment]
@iangeek Just when I thought I'd found the perfect solution. But it was a pretty glaring error given that they provide a most widely used webfonts. And they didn't allow us to source the svg version. I still think this is a good idea even if only for a month or so till it rolls out. If only to save me a bit of trouble on my projects.

**Comment by alfredxing** [comment]
I'll be developing this issue on the [svg-fonts](https://github.com/alfredxing/brick/tree/svg-fonts) branch. It'll probably take some time.

**Comment by alfredxing** [comment]
@kartikluke Added all of the SVG fonts and added a proper `<svg>` tag to each, but the `<font>` tag on each still needs to be changed. Do you want to do that?

**Comment by fluke** [comment]
Sorry, I don't have access to stable internet for a couple of days or so.
So I'll look into it as soon as I can.

**Comment by alfredxing** [comment]
OK, I made a short [Python script](https://gist.github.com/alfredxing/527e07f2d0429f4a063f) to replace all the font ID's and incorrect SVG tags, and ran it through. I'll check `brick.php` again and test the whole thing out!

**Comment by alfredxing** [comment]
Tweaked the PHP file a bit and everything should be okay. I'll submit a PR to merge this branch into master, we can discuss more there.

**Comment by fluke** [comment]
Sorry I wasn't able to help more currently in the process of shifting to a
new place.

**Comment by alfredxing** [comment]
@kartikluke That's fine, you've done quite a lot already. Thanks!

**Comment by alfredxing** [comment]
#85 is merged. Please re-open if you're still finding that fonts aren't rendering well.
