### ISSUE TITLE
Add Huerta Tipografica fonts

### ISSUE THREAD

**Issue by nagisa** [alfredxing/brick#8]
- [x] Alegreya HT
- [x] Alegreya Sans HT
- [x] Bitter HT
- [x] Telex HT Regular

There’s two versions of Alegreya HT, and only the non-OFL counterpart seems to be available from [their website](http://huertatipografica.com/). It looks like that one will have to be taken from [Google Web Fonts repository](https://code.google.com/p/googlefontdirectory/source/browse/ofl/alegreya/src).

**Comment by alfredxing** [comment]
Those look great, I'll add those soon for sure.

**Comment by alfredxing** [comment]
Added Bitter

**Comment by alfredxing** [comment]
Added Telex

**Comment by alfredxing** [comment]
Added Alegreya Sans

**Comment by alfredxing** [comment]
All done! Closing.
