### ISSUE TITLE
Aleo Italics kerning.

### ISSUE THREAD

**Issue by pygy** [alfredxing/brick#80]
There are several places were the kerning of Aleo Itlaics is wrong.

See `over filled` and `cry stall` below.

![screen shot 2014-07-30 at 10 29 50 pm](https://cloud.githubusercontent.com/assets/54515/3755793/73ac947a-1828-11e4-8cef-ba2cf408d418.png)
![screen shot 2014-07-30 at 10 30 00 pm](https://cloud.githubusercontent.com/assets/54515/3755794/73b2da38-1828-11e4-8afa-0db109e3b859.png)

Beside that, thanks for brick, it's really good overall.

**Comment by alfredxing** [comment]
The `fi` is a ligature (it's supposed to be like that). Not sure about the `ys` though, but I think it's a problem with the font itself and not brick. Any thoughts @AlessioLaiso?

**Comment by AlessioLaiso** [comment]
Thanks for the suggestions. 
/r and /fi look very apart and should be fixed.  The kerning between /y and /s could be slightly improved too. I'm very busy at the moment, but I will do it as soon as I manage, or you could do it if you know how to.

If you have other suggestions, please let me know.

**Comment by alfredxing** [comment]
@AlessioLaiso Thanks! I have no idea :stuck_out_tongue:

**Comment by pygy** [comment]
Sadly, I don't know how to edit fonts, and have no time to learn it ATM.

400i is fine, btw, and so are the roman fonts.

http://brick.im/fonts/aleo/

**Comment by pygy** [comment]
@AlessioLaiso @alfredxing I'm revisiting old issues... any news on this front?

**Comment by AlessioLaiso** [comment]
@pygy Not really from my side, I didn't get to work on it lately.

**Comment by AlessioLaiso** [comment]
I've created a pull request that updates the font files of Aleo to version 1.3. This version improves kerning, adds new glyphs and supports 34 new languages.
https://github.com/alfredxing/brick/pull/144

**Comment by pygy** [comment]
w000t :-)

Thus waiting for the #144 merge to close this.

Many thanks @AlessioLaiso

**Comment by alfredxing** [comment]
PR merged! The new version is now live.

**Comment by pygy** [comment]
Loaded from a fresh cache (private window) the  bold+italics variant still reads `over filled` and `cry stal`...

http://brick.im/fonts/aleo/

**Comment by AlessioLaiso** [comment]
@pigy I also still see the issues on Brick, but the new fonts look fine for me both in Glyphs and in Adobe CC software:
![image](https://cloud.githubusercontent.com/assets/7041012/22641966/bba442c4-ec50-11e6-8d6a-f2690507456a.png)

**Comment by alfredxing** [comment]
Oops, forgot to update something on the server! Should be fixed now. Let me know otherwise!

**Comment by AlessioLaiso** [comment]
@alfredxing Looks good now, thanks!
