### ISSUE TITLE
Add Ubuntu Font Family

### ISSUE THREAD

**Issue by curiositry** [alfredxing/brick#82]
The Ubuntu font family, designed by Dalton Maag, is one of my favourite sans-serif typefaces — and it’s distributed under an open licence!

Here’s the info:
- [Official Site](http://font.ubuntu.com)
- [License](http://font.ubuntu.com/licence)
- [Ubuntu on Google Fonts](https://www.google.com/fonts#UsePlace:use/Collection:Ubuntu)
- [Foundery](http://www.daltonmaag.com/)

**Comment by alfredxing** [comment]
Thanks! Added in b7e09f7f36e3c9ffa026fb4c88f1763f3408ff89.
