### ISSUE TITLE
Muli fonts showing as serif fallback for most weights on Chrome

### ISSUE THREAD

**Issue by iangeek** [alfredxing/brick#84]
This can actually be seen on http://brick.im/fonts/muli/.

Italics and 200 weight is fine, but all other non-italics are falling back to a serif on Win7 Chrome. Looks to be fine on Firefox. Not sure if this is a local issue or to do with any Chrome-targetted updates.

**Comment by alfredxing** [comment]
Hmm, looks fine for me on Chrome (OS X 10.9). Did you try clearing your cache in Chrome?

**Comment by iangeek** [comment]
Brand new Windows 7 system (only set up out of the box last night), so nothing even cached yet :) But I've cleared the cache anyway, and still no ball (see below).

Fine on Canary though, so guessing its something to do with the current Windows Chrome build again. Put it on back-burner for now in that case...

![muli](https://cloud.githubusercontent.com/assets/1556882/3814144/e24ab65c-1cb8-11e4-8a36-949d43c55b75.png)

**Comment by alfredxing** [comment]
Just booted up my Windows 8.1 machine and I can reproduce. I'll check the font files themselves as soon as I can.

**Comment by alfredxing** [comment]
Sorry for the wait! I've reconverted all of the WOFFs and purged the cache.

**Comment by alfredxing** [comment]
It works now on my Windows machine, can you confirm?

**Comment by iangeek** [comment]
Confirmed, all look as it should now. Good work,

**Comment by alfredxing** [comment]
Awesome!
