### ISSUE TITLE
Catalogue makes bad style links for long font names

### ISSUE THREAD

**Issue by curiositry** [alfredxing/brick#86]
When the catalogue generates style links for fonts with three word names, it uses a **space** instead of a **+** between the last two words, which doesn’t work.

For example, it produces:

``` css
<link rel="stylesheet" href="//brick.a.ssl.fastly.net/Latin+Modern Roman:400,700,400i,700i">
```

… which should be:  

``` css
<link rel="stylesheet" href="//brick.a.ssl.fastly.net/Latin+Modern+Roman:400,700,400i,700i">
```

Omphalosskeptic

**Comment by alfredxing** [comment]
Thanks for the report! Fixed.
