### ISSUE TITLE
Font Suggestion: BPReplay

### ISSUE THREAD

**Issue by etsnyman** [alfredxing/brick#88]
Hi! I suggest you start serving the font BPReplay. It is an libre/open font, and it is available under the SIL Open Font License.

Download link here:
http://backpacker.gr/font.asp?m=1&font=bp1

**Comment by alfredxing** [comment]
Looks like a nice font!

**Comment by alfredxing** [comment]
Thanks for the suggestion! Added in 3041535d8facb81ee03c88f33058cff6d92ac97d.

**Comment by etsnyman** [comment]
Great! Thanks! I will suggest some more as I come across them.
