### ISSUE TITLE
HTTP protocol missing in Usage docs

### ISSUE THREAD

**Issue by davidheijkamp** [alfredxing/brick#91]
In the Usage wiki all URL's seem to miss the HTTP protocol. Testing the fonts without HTTP seemed to work in most browsers, but the Android mail client failed to load the font. After adding HTTP to the link the fonts worked fine in this app as well.

P.S. I didn't realise I could indeed change the wiki, but I did. After that I saw the bucket on [brick.im](http://brick.im) also generates links without HTTP.

**Comment by alfredxing** [comment]
Usually not specifying the protocol means the browser can use the same protocol as the page the link is on. For example, on a page served on the HTTP protocol, the link would use HTTP as well, whereas on an HTTPS page, the link would be served with HTTPS.

I would recommend not including the protocol where possible, but of course if this doesn't work, you should include a protocol (I'd suggest HTTPS by default).

**Comment by davidheijkamp** [comment]
Ok, thanks for the explanation. Maybe wise to add this to the Usage instructions.

**Comment by alfredxing** [comment]
Definitely will when the new site goes up (it'll have the docs on the site for better accessibility).
