### ISSUE TITLE
Font Suggestion: Aileron

### ISSUE THREAD

**Issue by etsnyman** [alfredxing/brick#93]
Have you seen Aileron? It is a grotesque sans-serif with many weights and corrosponding obliques. Looks really great at large sizes. The creator has stopped development and released the family (which actually seems rather complete) into the public domain.
http://dotcolon.net/font/aileron/

**Comment by rstacruz** [comment]
I like it. :+1:

**Comment by alfredxing** [comment]
Added in #128
